---

- name: Create a new Linode.
  linode_v4:
    label: "{{ linode_label }}"
    access_token: "{{ token }}"
    type: g6-nanode-1
    region: us-east
    image: linode/alpine3.20
    root_pass: "{{ password }}"
    authorized_keys: "{{ ssh_keys }}"
    group: example_group
    tags: example_group
    state: present
  register: my_linode

- name: Print info about my Linode instance
  debug:
    msg: "ID is {{ my_linode.instance.id }} IP is {{ my_linode.instance.ipv4 }}"
