[package]
name = "wifi-verify-server"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
axum = { version = "0.7", features = ["ws"] }
axum-server = { version = "*", features = ["tls-rustls"] }
# axum-server = { version = "*", features = ["tls-rustls-no-provider"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["fs", "trace"] }
webrtc = "0.9"
tokio-tungstenite = "0.21"
futures = "0.3"
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = { version = "1.6", features = ["v4", "serde"] }
