---
# Simplified version (alternative)
- name: install local prerequisites
  hosts: localhost
  connection: local
  become: true
  gather_facts: false
  
  tasks:
    - name: Ensure packages are installed
      package: name={{ item }} update_cache=yes
      loop:
        - jq
