name: Build Binary

on:
  # push:
  #  branches:
  #    - main
  workflow_dispatch:

jobs:
  build-binary:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact_name: netpoke-x86_64-linux-musl-${{ github.sha }}
          # - os: ubuntu-latest
          #  target: aarch64-unknown-linux-musl
          #  artifact_name: netpoke-aarch64-linux-musl
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y podman-docker

      - name: Build release binary
        run: |
          pwd && ls -la 
          make build-everything

      - name: Deploy on sandbox
        run: |
          make deploy-sandbox


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}-lean
          path: |
            out/netpoke-server

      - name: Upload artifact with symbols
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}-symbols
          path: |
            out/netpoke-server-symbols



